/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProRouteImport } from './routes/pro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompteSuppressionRouteImport } from './routes/compte.suppression'
import { Route as ComptePauseRouteImport } from './routes/compte.pause'
import { Route as AuthenticatedMandataireRouteImport } from './routes/_authenticated/mandataire'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteSuppressionRoute = CompteSuppressionRouteImport.update({
  id: '/compte/suppression',
  path: '/compte/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptePauseRoute = ComptePauseRouteImport.update({
  id: '/compte/pause',
  path: '/compte/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMandataireRoute = AuthenticatedMandataireRouteImport.update({
  id: '/mandataire',
  path: '/mandataire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mandataire': typeof AuthenticatedMandataireRoute
  '/compte/pause': typeof ComptePauseRoute
  '/compte/suppression': typeof CompteSuppressionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mandataire': typeof AuthenticatedMandataireRoute
  '/compte/pause': typeof ComptePauseRoute
  '/compte/suppression': typeof CompteSuppressionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/pro': typeof ProRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/mandataire': typeof AuthenticatedMandataireRoute
  '/compte/pause': typeof ComptePauseRoute
  '/compte/suppression': typeof CompteSuppressionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/auth'
    | '/pro'
    | '/reset-password'
    | '/mandataire'
    | '/compte/pause'
    | '/compte/suppression'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/auth'
    | '/pro'
    | '/reset-password'
    | '/mandataire'
    | '/compte/pause'
    | '/compte/suppression'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/archives'
    | '/auth'
    | '/pro'
    | '/reset-password'
    | '/_authenticated/mandataire'
    | '/compte/pause'
    | '/compte/suppression'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArchivesRoute: typeof ArchivesRoute
  AuthRoute: typeof AuthRoute
  ProRoute: typeof ProRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ComptePauseRoute: typeof ComptePauseRoute
  CompteSuppressionRoute: typeof CompteSuppressionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/suppression': {
      id: '/compte/suppression'
      path: '/compte/suppression'
      fullPath: '/compte/suppression'
      preLoaderRoute: typeof CompteSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/pause': {
      id: '/compte/pause'
      path: '/compte/pause'
      fullPath: '/compte/pause'
      preLoaderRoute: typeof ComptePauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mandataire': {
      id: '/_authenticated/mandataire'
      path: '/mandataire'
      fullPath: '/mandataire'
      preLoaderRoute: typeof AuthenticatedMandataireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMandataireRoute: typeof AuthenticatedMandataireRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMandataireRoute: AuthenticatedMandataireRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArchivesRoute: ArchivesRoute,
  AuthRoute: AuthRoute,
  ProRoute: ProRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ComptePauseRoute: ComptePauseRoute,
  CompteSuppressionRoute: CompteSuppressionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
